import catalogJson from './catalog.fixture.json';

import { Streami18n } from '../../utils/i18n/Streami18n';
import { runtimeDefaults } from '../runtimeDefaults';
import { asDynamicKey } from '../utils';

/**
 * Every key in the generated catalog, rendered.
 *
 * This is the G2 guarantee at full scale: with no dictionary registered at all, not one of the
 * SDK's keys may surface as its own dotted path. A single missed call site — a key whose copy was
 * never bundled and whose call site passes no inline default — shows up here as the raw key.
 *
 * The catalog is a type-only module, so the fixture is its data twin, regenerated by
 * `yarn build-translations` alongside `keys.ts`.
 */

const catalog = catalogJson as Record<string, string>;
const PLURAL_SUFFIX = /_(zero|one|two|few|many|other)$/;
const DOTTED_KEY = /^[a-z][a-zA-Z0-9]*(\.[a-zA-Z0-9]+)+$/;

/** `{{ timestamp | timestampFormatter(...) }}` and friends resolve through a formatter, not copy. */
const isFormatterExpression = (copy: string) => /\{\{.*\|.*\}\}/.test(copy);

/**
 * A value for every placeholder the copy declares. Not every plural key interpolates `count` —
 * `channelDetails.presence.membersOnline.label` uses `memberCount` and `onlineCount` — so the
 * variables have to be read off the copy rather than assumed.
 */
const interpolationArgs = (copy: string) =>
  Object.fromEntries([...copy.matchAll(/\{\{\s*([\w]+)\s*\}\}/g)].map(([, name]) => [name, 3]));

describe('every catalog key renders copy, never its own key path', () => {
  let t: Streami18n['t'];

  beforeAll(async () => {
    // Deliberately bare: no language, no dictionary, no overrides.
    const i18n = new Streami18n({ logger: () => {} });
    ({ t } = await i18n.init());
  });

  const bases = new Set<string>();
  const singulars: string[] = [];
  for (const key of Object.keys(catalog)) {
    if (PLURAL_SUFFIX.test(key)) bases.add(key.replace(PLURAL_SUFFIX, ''));
    else singulars.push(key);
  }

  it('covers the whole catalog', () => {
    expect(singulars.length + bases.size).toBeGreaterThan(300);
  });

  it.each(singulars)('%s', (key) => {
    const copy = catalog[key];
    const bundled = key in runtimeDefaults;

    // Bundled keys resolve from runtimeDefaults; prose keys pass their copy inline, exactly as the
    // call sites do.
    const rendered = bundled
      ? t(asDynamicKey(key), {
          ...interpolationArgs(copy),
          milliseconds: 1000,
          timestamp: new Date(0),
        })
      : t(asDynamicKey(key), copy, interpolationArgs(copy));

    expect(rendered).not.toBe(key);
    if (!isFormatterExpression(copy)) {
      expect(rendered).not.toMatch(DOTTED_KEY);
    }
  });

  it.each([...bases])('%s (plural)', (base) => {
    for (const count of [0, 1, 2, 5]) {
      const rendered = t(asDynamicKey(base), {
        ...interpolationArgs(catalog[`${base}_other`]),
        count,
        defaultValue_one: catalog[`${base}_one`],
        defaultValue_other: catalog[`${base}_other`],
      });

      expect(rendered).not.toBe(base);
      expect(rendered).not.toMatch(DOTTED_KEY);
      // The count has to have been interpolated, not left as a literal placeholder.
      expect(rendered).not.toContain('{{');
    }
  });
});
