// AUTO-GENERATED by scripts/generate-i18n-keys.mts — do not edit by hand.
// Regenerate with `yarn build-translations`. CI fails if this file is out of sync.
//
// Type-only: no runtime value is emitted, so this adds nothing to the bundle.

/**
 * Every translation entry shipped with the SDK, mapped to its English copy.
 *
 * Plural entries appear as `<key>_one` / `<key>_other`; call sites use the bare `<key>` and
 * pass `count`. See {@link TranslationKey}.
 */
export type TranslationCatalog = {
  'duration.messageReminder': '{{ milliseconds | durationFormatter(withSuffix: true) }}';
  'timestamp.ChannelPreviewStatus': '{{ timestamp | timestampFormatter(calendar: true; calendarFormats: {"lastDay":"[Yesterday]", "lastWeek":"dddd", "nextDay":"[Tomorrow]", "nextWeek":"dddd [at] LT", "sameDay":"LT", "sameElse":"L"}) }}';
  'timestamp.FileAttachmentListSection': '{{ timestamp | timestampFormatter(format: MMMM YYYY) }}';
  'timestamp.ImageGalleryHeader': '{{ timestamp | timestampFormatter(calendar: true) }}';
  'timestamp.InlineDateSeparator': '{{ timestamp | timestampFormatter(calendar: true) }}';
  'timestamp.MessageSystem': '{{ timestamp | timestampFormatter(calendar: true) }}';
  'timestamp.MessageTimestamp': '{{ timestamp | timestampFormatter(format: LT) }}';
  'timestamp.PollVote': '{{ timestamp | relativeCompactDateFormatter }}';
  'timestamp.StickyHeader': '{{ timestamp | timestampFormatter(calendar: true) }}';
  'timestamp.ThreadListItem': '{{ timestamp | timestampFormatter(calendar: true; calendarFormats: {"lastDay":"[Yesterday]", "lastWeek":"dddd", "nextDay":"[Tomorrow]", "nextWeek":"dddd [at] LT", "sameDay":"LT", "sameElse":"L"}) }}';
  'timestamp.UserActivityStatus': 'Last seen {{ timestamp | fromNowFormatter }}';
};
