name: build

on:
  push:
    branches:
      - v2-designs
jobs:
  build_and_deploy_ios:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install RubyGems
        run: |
          cd examples/SampleApp/ios
          bundle update --bundler
      - name: Install firebase-tools
        run: npm install -g firebase-tools
      - name: RN setup
        run: |
          yarn;
          cd native-package
          yarn;
          cd ../examples/SampleApp
          yarn;
          cd ios
          pod install
      - name: Build and release
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          cd examples/SampleApp/ios
          bundle exec fastlane distribute

  build_and_deploy_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: RN setup
        run: |
          yarn add global react-native-cli;
          yarn;
          cd native-package
          yarn;
          cd ../examples/SampleApp
          yarn;
      - name: Build
        run: |
          cd examples/SampleApp
          mkdir android/app/src/main/assets
          mkdir tmp
          yarn react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest tmp
          cd android
          rm -rf $HOME/.gradle/caches/ && ./gradlew assembleRelease
      - name: Deploy
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{secrets.ANDROID_FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: android-react-native-testers
          file: examples/SampleApp/android/app/build/outputs/apk/release/app-release.apk
