name: Changelog preview

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  generate_changelog_preview:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 24.x ]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: develop
          # pulls all commits (needed for semantic release to correctly version)
          fetch-depth: '0'
      # pulls all tags (needed for semantic release to correctly version)
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Install Linux build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Installation
        run: yarn install --immutable

      - name: Generate Changelog
        id: generate_changelog
        run: |
          GITHUB_REF='refs/heads/develop' yarn extract-changelog
          echo "Changelog script finished! Checking if there are changes..."
          CHANGELOG_PREVIEW=$(cat NEXT_RELEASE_CHANGELOG.md || true)

          if [[ ! -z "${CHANGELOG_PREVIEW}" ]]; then
            echo "Changelog found! Writing header to the file..."
            echo '# Next releases' | cat - NEXT_RELEASE_CHANGELOG.md > NEXT_RELEASE_CHANGELOG.tmp.md && mv NEXT_RELEASE_CHANGELOG.tmp.md NEXT_RELEASE_CHANGELOG.md

            echo "Changelog file ready! Setting up outputs"
            CHANGELOG_PREVIEW=$(cat NEXT_RELEASE_CHANGELOG.md)

            echo "exists=true" >> "$GITHUB_OUTPUT"
            {
              echo "preview<<CHANGELOG_PREVIEW_EOF"
              echo "$CHANGELOG_PREVIEW"
              echo "CHANGELOG_PREVIEW_EOF"
            } >> "$GITHUB_OUTPUT"
          fi
      - uses: marocchino/sticky-pull-request-comment@v3
        if: steps.generate_changelog.outputs.exists == 'true'
        with:
          header: changelog_preview
          message: ${{ steps.generate_changelog.outputs.preview }}
      - uses: marocchino/sticky-pull-request-comment@v3
        if: steps.generate_changelog.outputs.exists != 'true'
        with:
          header: changelog_preview
          message: No changelog generated for the current changes on this pull request.
