name: Check Docusaurus docs with Vale linter

on: [pull_request]

jobs:
  vale:
    name: Vale doc linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@reviewdog
        with:
          # added, diff_context, file, nofilter
          # Default is added: results are filtered for added/modified files. Set to no filter when all files need to be checked.
          # More info: https://github.com/errata-ai/vale-action and https://github.com/reviewdog/reviewdog#filter-mode
          filter_mode: nofilter
          # github-pr-check, github-pr-review, github-check
          reporter: github-pr-check
          # Set fail_on_error to true to make sure builds fail.
          fail_on_error: true
          files: docusaurus
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
